# Generated by Django 3.2.5 on 2021-08-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeLv', models.IntegerField(default=1, verbose_name='属性级别')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='属性名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='属性简介')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute_problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute_problem_Lv', models.IntegerField(default=1, verbose_name='问题属性级别')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='问题属性名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='问题属性简介')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentProblemPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_Attribute_problem', models.IntegerField(default=0, verbose_name='上个问题属性id')),
                ('up_Attribute_problemName', models.CharField(default='无', max_length=100, null=True, verbose_name='上个问题属性名称')),
                ('down_Attribute_problem', models.IntegerField(unique=True, verbose_name='当前问题属性id')),
                ('down_Attribute_problemName', models.CharField(max_length=100, null=True, verbose_name='当前问题属性名称')),
                ('up_Prototype', models.IntegerField(default=0, verbose_name='原型id')),
                ('up_PrototypeName', models.CharField(default='无', max_length=100, null=True, verbose_name='原型名称')),
                ('successNum', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failNum', models.IntegerField(default=0, verbose_name='失败次数')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='目标名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='目标简介')),
            ],
        ),
        migrations.CreateModel(
            name='ObjInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='对象实例名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='对象实例简介')),
                ('attributeId', models.JSONField(null=True, verbose_name='Attribute属性id')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='计划名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='计划简介')),
                ('step', models.IntegerField(default=1, verbose_name='序号')),
                ('objectiveId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objClass.objective', verbose_name='目标id')),
            ],
        ),
        migrations.CreateModel(
            name='PlanStepProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='计划问题名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='计划问题简介')),
                ('problemJson', models.JSONField(max_length=2000, null=True, verbose_name='问题属性json')),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objClass.plan', verbose_name='计划id')),
            ],
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='原型名')),
                ('up_Attribute', models.IntegerField(verbose_name='上个属性id')),
                ('up_AttributeName', models.CharField(max_length=100, null=True, verbose_name='上个属性名称')),
                ('down_Attribute', models.IntegerField(verbose_name='下个属性id')),
                ('down_AttributeName', models.CharField(max_length=100, null=True, verbose_name='下个属性名称')),
                ('relation', models.IntegerField(verbose_name='关系id')),
                ('relationName', models.CharField(max_length=100, null=True, verbose_name='关系名称')),
                ('step', models.IntegerField(verbose_name='序号')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationLv', models.IntegerField(default=1, verbose_name='属性级别')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='属性名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='属性简介')),
            ],
        ),
        migrations.CreateModel(
            name='PlanStepProblemScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='计划问题名')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='计划问题简介')),
                ('result', models.IntegerField(default=2, verbose_name='方案结果')),
                ('schemeJson', models.JSONField(max_length=2000, null=True, verbose_name='方案json')),
                ('planStepProblemId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objClass.planstepproblem', verbose_name='计划问题id')),
            ],
        ),
    ]
