# Generated by Django 3.2.5 on 2021-08-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objClass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstepproblem',
            name='step',
            field=models.IntegerField(default=1, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='planstepproblemscheme',
            name='step',
            field=models.IntegerField(default=1, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='environmentproblemprototype',
            name='down_Attribute_problem',
            field=models.IntegerField(verbose_name='当前问题属性id'),
        ),
    ]
