# Generated by Django 3.2.5 on 2021-08-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objClass', '0002_auto_20210806_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstepproblem',
            name='down_planStepProblemId',
            field=models.IntegerField(null=True, verbose_name='下个问题id'),
        ),
        migrations.AddField(
            model_name='planstepproblem',
            name='up_planStepProblemId',
            field=models.IntegerField(null=True, verbose_name='上个问题id'),
        ),
    ]
