# Generated by Django 3.2.5 on 2021-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objClass', '0003_auto_20210827_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planstepproblem',
            name='down_planStepProblemId',
            field=models.JSONField(null=True, verbose_name='下个问题id'),
        ),
        migrations.AlterField(
            model_name='planstepproblem',
            name='up_planStepProblemId',
            field=models.JSONField(null=True, verbose_name='上个问题id'),
        ),
    ]
