# Generated by Django 3.2.5 on 2021-08-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objClass', '0004_auto_20210827_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='原型名'),
        ),
    ]
